# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ed7062202ea04e1df07e6a8d6b64023c0a5c34690c0cea06c7d9df637a39bfc0ab919512f9ed300cce41c0fcaaf6ed352bcb94d08adb204fd32161b099b8d89

test:
  secret_key_base: 180df7d6b871f755ef559615cfd7bd182037e833b32232157d78cd8c3d82d726a5aff91ac617d9247fd103d247647089834aa8c426b9e8fe0c3cbb3178e3b3f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
